# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# A1b.py
# Created on: 2019-02-14 12:31:36.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import time
import numpy
startTime = time.time()
arcpy.env.overwriteOutput = True

# Local variables:
# var for suitAg
nestream = "nestream"
Output_direction_raster__2_ = ""
nesandp = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\nesandp"
Output_direction_raster__4_ = ""
nelu95 = "nelu95"
Reclass_nelu1 = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Reclass_nelu1"
Input_raster_or_constant_value_1 = "101"
nedem = "nedem"
Agr_slope = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Agr_slope"
Agr_slope_slice = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Agr_slope_slice"
Agr_minus_slope = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Agr_minus_slope"
Agr_Dis_stream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Agr_Dis_stream"
Agr_slice_stream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Agr_slice_stream"
Input_raster_or_constant_value_1__2_ = "101"
EucDist_Clay = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\EucDist_Clay"
Slice_clay = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Slice_clay"
Minus_clay = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Minus_clay"
nelu95__2_ = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\nelu95"
Agr_95dev = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\Dev.gdb\\Agr_95dev"
Euc_Agr = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\Dev.gdb\\Euc_Agr"
Agr_95dev_slice = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\Dev.gdb\\Agr_95dev_slice"
AHP_Agr = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\AHP_Agr"
SuitAgr = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\SuitAgr"
SuitSliceAgr = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\SuitSliceAgr"
Output_direction_raster__3_ = ""

# var for suitDev
neroads = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\neroads"
Plannable_Roads = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Reclass_nero1"
Output_direction_raster = ""
nestream = "nestream"
re_stream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\re-stream"
Output_direction_raster__2_ = ""
neaa = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\neaa"
A_reclass = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\a-reclass"
Output_direction_raster__4_ = ""
nedem = "nedem"
slope__2_ = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\slope"
Input_raster_or_constant_value_1 = "101"
slope__3_ = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\slope"
slice_slope = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\slice_slope"
minus_slope = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\minus_slope"
stream_dis = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\stream-dis"
stream_slice = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\stream-slice"
Input_raster_or_constant_value_1__2_ = "101"
A_dist = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\a-dist"
A_slice = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\a-slice"
minus_aa = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\minus_aa"
Input_raster_or_constant_value_1__3_ = "101"
road_distance = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\road-distance"
road_sli = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\road_sli"
minus_roads = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\minus-roads"
AHP = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\ahp"
nelu95 = "nelu95"
reclassify_dev95 = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\Dev.gdb\\reclassify_dev95"
suitDev = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\suitdev"
Dev_slice = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Dev_slice"

# var for suitNat
nelu95__2_ = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\nelu95"
Reclass_wetland = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\mbtutor\\mbtutor\\scratch\\scratch.gdb\\Reclass_wetland"
R2T_nelu95b = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\R2T_nelu95b"
Output_direction_raster__2_ = ""
nestream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\nestream"
Output_direction_raster__3_ = ""
nepreset = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\nepreset"
Output_direction_raster__4_ = ""
nelu95 = "nelu95"
landuse_legend_dbf = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\landuse_legend.dbf"
Reclass_nelu_nowater = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Reclass_nelu_nowater"
nedem = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\nedem"
Slope_dem = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Slope_dem"
Slice_Slope = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Slice_Slope"
EucDist_vege = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\mbtutor\\mbtutor\\scratch\\scratch.gdb\\EucDist_vege"
Slice_vege = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Slice_vege"
Input_raster_or_constant_value_1 = "101"
EucDist_stream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\mbtutor\\mbtutor\\scratch\\scratch.gdb\\EucDist_stream"
Reclass_stream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\mbtutor\\mbtutor\\scratch\\scratch.gdb\\Reclass_stream"
Minus_stream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Minus_stream"
Input_raster_or_constant_value_1__2_ = "101"
EucDist_R2T_wetland = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\mbtutor\\mbtutor\\scratch\\scratch.gdb\\EucDist_R2T_wetland"
Slice_wetland = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Slice_wetland"
Minus_wetland = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Minus_wetland"
Weighte_composite = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Weighte_composite"
suitNat = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\mbtutor\\mbtutor\\scratch\\scratch.gdb\\suitNat"


#Local variables for 1b
nelu95__2_ = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\nelu95"
reclass_nelu95_avail = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1b.gdb\\reclass_nelu95_avail"
nestream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1_MCE\\A1_MCE\\nestream"
Raster_cal = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1b.gdb\\Raster_cal"
Avail_stream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1b.gdb\\Avail_stream"
Times_nelu95_avastream = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1b.gdb\\Times_nelu95_avastream"
Dev_slice = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Dev_slice"
suitNat = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\suitNat"
SuitSliceAgr = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\SuitSliceAgr"
Highest_Dev_1 = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Highest_Dev_1"
nelu95 = "nelu95"
Nelu_relassified = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1b.gdb\\Nelu_relassified"
Over_futureland = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1b.gdb\\Over_futureland"
Times2 = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1b.gdb\\Times2"
Reclass_Time2 = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Reclass_Time2"
Slice_futureland = "C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1b.gdb\\Slice_futureland"




# suitNat starts
# Process: Slope
arcpy.gp.Slope_sa(nedem, Agr_slope, "DEGREE", "0.3048", "PLANAR", "METER")

# Process: Slice (3)
arcpy.gp.Slice_sa(Agr_slope, Agr_slope_slice, "100", "EQUAL_INTERVAL", "1")

# Process: Minus
arcpy.gp.Minus_sa(Input_raster_or_constant_value_1, Agr_slope_slice, Agr_minus_slope)

# Process: Euclidean Distance (2)
arcpy.gp.EucDistance_sa(nestream, Agr_Dis_stream, "", "30", Output_direction_raster__2_, "PLANAR")

# Process: Slice (2)
arcpy.gp.Slice_sa(Agr_Dis_stream, Agr_slice_stream, "100", "EQUAL_INTERVAL", "1")

# Process: Reclassify (4)
arcpy.gp.Reclassify_sa(nelu95__2_, "VALUE", "111 194 1;194 625 0", Agr_95dev, "DATA")

# Process: Euclidean Distance (3)
arcpy.gp.EucDistance_sa(Agr_95dev, Euc_Agr, "", "30", Output_direction_raster__3_, "PLANAR")

# Process: Slice (6)
arcpy.gp.Slice_sa(Euc_Agr, Agr_95dev_slice, "100", "EQUAL_INTERVAL", "1")

# Process: Euclidean Distance (4)
arcpy.gp.EucDistance_sa(nesandp, EucDist_Clay, "", "30", Output_direction_raster__4_, "PLANAR")

# Process: Slice (4)
arcpy.gp.Slice_sa(EucDist_Clay, Slice_clay, "100", "EQUAL_INTERVAL", "1")

# Process: Minus (2)
arcpy.gp.Minus_sa(Input_raster_or_constant_value_1__2_, Slice_clay, Minus_clay)

# Process: Weighted Sum
arcpy.gp.WeightedSum_sa("'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Agr_minus_slope' VALUE 0.59;'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Agr_slice_stream' VALUE 0.13;'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Minus_clay' VALUE 0.2;'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\Dev.gdb\\Agr_95dev_slice' VALUE 0.08", AHP_Agr)

# Process: Reclassify
arcpy.Reclassify_3d(nelu95, "nelu95.vat:VALUE", "111 194 0;194 429 1;429 740 0", Reclass_nelu1, "DATA")

# Process: Times
arcpy.gp.Times_sa(Reclass_nelu1, AHP_Agr, SuitAgr)

# Process: Slice (5)
arcpy.gp.Slice_sa(SuitAgr, SuitSliceAgr, "100", "EQUAL_AREA", "1")
# suitNat ends



# suitDev starts
# Process: Reclassify (2)
arcpy.gp.Reclassify_sa(nestream, "VALUE", "6 0;7 0;8 0", re_stream, "DATA")

# Process: Euclidean Distance (2)
arcpy.gp.EucDistance_sa(re_stream, stream_dis, "", "30", Output_direction_raster__2_, "PLANAR")

# Process: Slice (2)
arcpy.gp.Slice_sa(stream_dis, stream_slice, "100", "EQUAL_INTERVAL", "1")

# Process: Slope
arcpy.gp.Slope_sa(nedem, slope__2_, "DEGREE", "0.3048", "PLANAR", "METER")

# Process: Slice (3)
arcpy.gp.Slice_sa(slope__3_, slice_slope, "100", "EQUAL_INTERVAL", "1")

# Process: Minus
arcpy.gp.Minus_sa(Input_raster_or_constant_value_1, slice_slope, minus_slope)

# Process: Reclassify (3)
arcpy.gp.Reclassify_sa(neaa, "VALUE", "0 NODATA;1 1", A_reclass, "DATA")

# Process: Euclidean Distance (4)
arcpy.gp.EucDistance_sa(A_reclass, A_dist, "", "30", Output_direction_raster__4_, "PLANAR")

# Process: Slice (4)
arcpy.gp.Slice_sa(A_dist, A_slice, "100", "EQUAL_INTERVAL", "1")

# Process: Minus (2)
arcpy.gp.Minus_sa(Input_raster_or_constant_value_1__2_, A_slice, minus_aa)

# Process: Reclassify
arcpy.gp.Reclassify_sa(neroads, "VALUE", "2 0;3 0;4 0;9 0;18 0", Plannable_Roads, "DATA")

# Process: Euclidean Distance
arcpy.gp.EucDistance_sa(Plannable_Roads, road_distance, "", "30", Output_direction_raster, "PLANAR")

# Process: Slice
arcpy.gp.Slice_sa(road_distance, road_sli, "100", "EQUAL_INTERVAL", "1")

# Process: Minus (3)
arcpy.gp.Minus_sa(Input_raster_or_constant_value_1__3_, road_sli, minus_roads)

# Process: Weighted Sum
arcpy.gp.WeightedSum_sa("'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\minus_slope' VALUE 0.07;'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\stream-slice' VALUE 0.49;'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\minus_aa' VALUE 0.16;'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\Gan geog 381\\geog 381\\geog381\\A1_MCE\\A1_MCE\\minus-roads' VALUE 0.28", AHP)

# Process: Reclassify (4)
arcpy.Reclassify_3d(nelu95, "nelu95.vat:VALUE", "111 194 0;194 429 1;429 625 0", reclassify_dev95, "DATA")

# Process: Times
arcpy.gp.Times_sa(AHP, reclassify_dev95, suitDev)

# Process: Slice (5)
arcpy.gp.Slice_sa(suitDev, Dev_slice, "100", "EQUAL_AREA", "1")
# suitDev ends



# suitNat starts
# Process: Reclassify (3)
arcpy.gp.Reclassify_sa(nelu95__2_, "VALUE", "111 530 NODATA;530 625 1", Reclass_wetland, "DATA")

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(Reclass_wetland, R2T_nelu95b, "SIMPLIFY", "VALUE", "SINGLE_OUTER_PART", "")

# Process: Euclidean Distance (2)
arcpy.gp.EucDistance_sa(R2T_nelu95b, EucDist_R2T_wetland, "", "73.08", Output_direction_raster__2_, "PLANAR")

# Process: Slice (2)
arcpy.gp.Slice_sa(EucDist_R2T_wetland, Slice_wetland, "100", "EQUAL_INTERVAL", "1")

# Process: Minus (2)
arcpy.gp.Minus_sa(Input_raster_or_constant_value_1__2_, Slice_wetland, Minus_wetland)

# Process: Euclidean Distance (3)
arcpy.gp.EucDistance_sa(nestream, EucDist_stream, "", "30", Output_direction_raster__3_, "PLANAR")

# Process: Reclassify (2)
arcpy.gp.Reclassify_sa(EucDist_stream, "VALUE", "", Reclass_stream, "DATA")

# Process: Minus
arcpy.gp.Minus_sa(Input_raster_or_constant_value_1, Reclass_stream, Minus_stream)

# Process: Euclidean Distance (4)
arcpy.gp.EucDistance_sa(nepreset, EucDist_vege, "", "30", Output_direction_raster__4_, "PLANAR")

# Process: Slice (3)
arcpy.gp.Slice_sa(EucDist_vege, Slice_vege, "100", "EQUAL_INTERVAL", "1")

# Process: Slope
arcpy.gp.Slope_sa(nedem, Slope_dem, "DEGREE", "1", "PLANAR", "METER")

# Process: Slice
arcpy.gp.Slice_sa(Slope_dem, Slice_Slope, "100", "EQUAL_INTERVAL", "1")

# Process: Weighted Sum
arcpy.gp.WeightedSum_sa("'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Slice_Slope' VALUE 0.57;'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Slice_vege' VALUE 0.16;'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Minus_stream' VALUE 0.2;'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Minus_wetland' VALUE 0.07", Weighte_composite)

# Process: Reclassify
arcpy.Reclassify_3d(nelu95, "nelu95.vat:VALUE", "111 0;112 1;113 2;115 3;121 4;122 5;124 6;126 7;128 8;131 9;134 10;138 11;141 12;142 13;144 14;145 15;146 16;171 17;172 18;193 19;194 20;210 21;220 22;230 23;240 24;250 25;290 26;310 27;320 28;412 29;421 30;429 31;510 32;520 33;530 34;611 35;613 36;622 37;625 38", Reclass_nelu_nowater, "DATA")

# Process: Times
arcpy.gp.Times_sa(Reclass_nelu_nowater, Weighte_composite, suitNat)
# suitNat ends



# 1b starts
# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("Con(IsNull(\"%nestream%\"),1, \"%nestream%\")", Raster_cal)

# Process: Reclassify (3)
arcpy.gp.Reclassify_sa(nelu95__2_, "VALUE", "111 194 0;194 429 1;429 625 0", reclass_nelu95_avail, "DATA")

# Process: Reclassify (2)
arcpy.gp.Reclassify_sa(Raster_cal, "VALUE", "1 1;1 6 NODATA;6 7 NODATA;7 8 NODATA", Avail_stream, "DATA")

# Process: Times
arcpy.gp.Times_sa(reclass_nelu95_avail, Avail_stream, Times_nelu95_avastream)

# Process: Reclassify
arcpy.Reclassify_3d(nelu95, "nelu95.vat:VALUE", "111 200 1;200 300 2;300 625 3", Nelu_relassified, "DATA")

# Process: Highest Position
arcpy.gp.HighestPosition_sa("'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\Dev_slice';'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\suitNat';'C:\\Users\\q5kang\\OneDrive - University of Waterloo\\381A1\\A1map\\A1.gdb\\SuitSliceAgr'", Highest_Dev_1)

# Process: Over
arcpy.gp.Over_sa(Highest_Dev_1, Nelu_relassified, Over_futureland) 

# Process: Times (2)
arcpy.gp.Times_sa(Times_nelu95_avastream, Over_futureland, Times2)

# Process: Reclassify (4)
arcpy.Reclassify_3d(Times2, "VALUE", "0 NODATA;0 1 1;1 2 2;2 3 3", Reclass_Time2, "DATA")

# Process: Slice
arcpy.Slice_3d(Reclass_Time2, Slice_futureland, "100", "EQUAL_AREA", "1")
# 1b process ends 


